USE [master]
GO
/****** Object:  Database [SD]    Script Date: 07/03/2024 02:19:38 ص ******/
CREATE DATABASE [SD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SD', FILENAME = N'D:\My Project\SQL\SD\SD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SD_log', FILENAME = N'D:\My Project\SQL\SD\SD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SD] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SD] SET ARITHABORT OFF 
GO
ALTER DATABASE [SD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SD] SET RECOVERY FULL 
GO
ALTER DATABASE [SD] SET  MULTI_USER 
GO
ALTER DATABASE [SD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SD', N'ON'
GO
ALTER DATABASE [SD] SET QUERY_STORE = ON
GO
ALTER DATABASE [SD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SD]
GO
/****** Object:  User [ma]    Script Date: 07/03/2024 02:19:39 ص ******/
CREATE USER [ma] FOR LOGIN [ma] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Schema [hr]    Script Date: 07/03/2024 02:19:39 ص ******/
CREATE SCHEMA [hr]
GO
/****** Object:  Table [dbo].[Dept]    Script Date: 07/03/2024 02:19:39 ص ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dept](
	[Dept_id] [int] NOT NULL,
	[dname] [varchar](20) NULL,
 CONSTRAINT [c] PRIMARY KEY CLUSTERED 
(
	[Dept_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[emp]    Script Date: 07/03/2024 02:19:39 ص ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[emp](
	[eid] [int] IDENTITY(1,1) NOT NULL,
	[ename] [varchar](20) NOT NULL,
	[eadd] [varchar](20) NULL,
	[hiredate] [date] NULL,
	[sal] [int] NULL,
	[overtime] [int] NULL,
	[nesal]  AS (isnull([sal],(0))+isnull([overtime],(0))) PERSISTED,
	[BD] [date] NULL,
	[age]  AS (datepart(year,getdate())-datepart(year,[BD])),
	[gender] [varchar](1) NULL,
	[hour_rete] [int] NOT NULL,
	[did] [int] NULL,
 CONSTRAINT [c1] PRIMARY KEY CLUSTERED 
(
	[eid] ASC,
	[ename] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [c2] UNIQUE NONCLUSTERED 
(
	[sal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [c3] UNIQUE NONCLUSTERED 
(
	[overtime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 07/03/2024 02:19:39 ص ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[SSN] [int] NOT NULL,
	[FirsN] [varchar](50) NOT NULL,
	[LastN] [varchar](20) NULL,
	[Gender] [varchar](1) NULL,
	[Dnum] [int] NULL,
	[supeid] [int] NULL,
	[BD] [date] NULL,
	[age] [int] NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[SSN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[mytest]    Script Date: 07/03/2024 02:19:39 ص ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[mytest](
	[id] [int] NULL,
	[name] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Porject]    Script Date: 07/03/2024 02:19:39 ص ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Porject](
	[Pnum] [int] NOT NULL,
	[pname] [varchar](50) NULL,
	[city] [varchar](50) NULL,
	[loc] [varchar](50) NULL,
	[Dnum] [int] NULL,
 CONSTRAINT [PK_Porject] PRIMARY KEY CLUSTERED 
(
	[Pnum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [hr].[work]    Script Date: 07/03/2024 02:19:39 ص ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [hr].[work](
	[SSN] [int] NOT NULL,
	[Pnumber] [int] NOT NULL,
	[Hours] [nchar](10) NULL,
 CONSTRAINT [PK_work] PRIMARY KEY CLUSTERED 
(
	[SSN] ASC,
	[Pnumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[emp] ADD  DEFAULT (getdate()) FOR [hiredate]
GO
ALTER TABLE [dbo].[emp]  WITH CHECK ADD  CONSTRAINT [c4] CHECK  (([sal]>(1000)))
GO
ALTER TABLE [dbo].[emp] CHECK CONSTRAINT [c4]
GO
ALTER TABLE [dbo].[emp]  WITH CHECK ADD  CONSTRAINT [c5] CHECK  (([eadd]='alex' OR [eadd]='mansoura' OR [eadd]='cairo'))
GO
ALTER TABLE [dbo].[emp] CHECK CONSTRAINT [c5]
GO
ALTER TABLE [dbo].[emp]  WITH CHECK ADD  CONSTRAINT [c6] CHECK  (([gender]='f' OR [gender]='m'))
GO
ALTER TABLE [dbo].[emp] CHECK CONSTRAINT [c6]
GO
ALTER TABLE [dbo].[emp]  WITH CHECK ADD  CONSTRAINT [c7] CHECK  (([overtime]>=(100) AND [overtime]<=(500)))
GO
ALTER TABLE [dbo].[emp] CHECK CONSTRAINT [c7]
GO
USE [master]
GO
ALTER DATABASE [SD] SET  READ_WRITE 
GO
